### ISSUE TITLE
Windows support? (gcc flag defaulted on pip install)

### ISSUE THREAD

**Issue by AaronCritchley** [quantopian/warp_prism#11]
Hey - thanks for the great work.

I build code for both Windows and Linux and would love to use `warp_prism`. When trying to `pip install` on Windows though, I get an error when compiling:
```
cl : Command line error D8021 : invalid numeric argument '/Wextra'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

With /Wextra being a gcc flag, it's failing when trying to use that with cl.

I am happy to PR to fix this if Windows support is expected, but wanted to first check if Windows is intended to be supported?

Happy to provide more info if needed.

**Comment by llllllllll** [comment]
Thanks for trying warp prism. We don't use windows so we haven't tried building warp prism for windows yet. If you want to open a PR that conditionally adds these flags depending on the os, we would definitely accept that.

The code is C99, so there shouldn't be any issues building with msvc; however, we do overflow checked arithmetic in a lot of places with the following code:

```c
#if __GNUC__ >= 5
#define add_overflow __builtin_add_overflow
#define mul_overflow __builtin_mul_overflow
#else
static inline bool add_overflow(size_t a, size_t b, size_t* out) {
    *out = a + b;
    return *out < a;
}

static inline bool mul_overflow(size_t a, size_t b, size_t* out) {
    *out = a * b;
    return a > SIZE_MAX / b;
}
#endif
```

GCC with optimizations can often make the non-intrinsic code generate the same jc-based jump, but there might be better way to do this with MSVC.

**Comment by AaronCritchley** [comment]
Thanks for the speedy reply, I'll look into adding windows support when I next have some time (likely next week), will either raise a PR or comment back on the issue to update on how it goes.

Thanks again!

**Comment by AaronCritchley** [comment]
Hey, sorry for taking so long to update.

I've taken a look and it looks like it will be slightly more involved than just removing the compile flags, I'll try in the background but it might be a while before I find time to properly dig in. I'll close the issue for now as I realise Windows users are definitely the minority 😄 

Thanks again for your help!
